export const API = {
  EXCELDATA: "/stg_trn_data/",
  FETCHERRORDATA: "/err_trn_data_tab/",
  UPDATEERRORDATA: "/delete_err_trn/",
  GETHIER2DATA: "/lov_item_dtl/",
  GETLOCATIONDATA: "/location_validation/",
  FETCHCONFIGDATA: "/system_config_tab/",
  UPDATECONFIGDATA: "/sys_conf/",
  DAILYCOUNTDATA: "/count_pending/",
  STAGECOUNTDATA: "/count_stg_trn/",
  ERRORCOUNTDATA: "/count_trn/",
  FETCHDAILYRECDATA: "/daily_rec/",
  FETCHERRSTAGESATA: "/retrieve_err_stg_data/",
  UPDATETRANSACTIONREVERSAL: "/trn_data_rev/",
  FETCHTRANSACTIONREVERSAL: "/trn_data_history/",
  CANCELTRANSACTIONREVERSAL: "/cancel/",
  FETCHITEMLOCATIONDATA: "/item_loc_data/",
  UPDATECOSTANDVAR: "/cost_update_stg_trn/",
  FETCHGLACCOUNT: "/gl_account_tab/",
  UPDATEGLACCOUNT: "/GL_ACCOUNT_update/",
  GETGLDATA: "/currency_gl/",
  INSERTGLDATA: "/GL_ACCOUNT_create/",
  FETCHSTGFIN: "/Retrieve_stg_fin/",
  FETCHTRNTYPE: "/trn_type_dtl/",
  FETCHTRNTYPELIST: "/trn_type_dtl_list/",
  FETCHDAILYVIEW: "/Daily_view/",
  FETCHSUBLEDGERCOST: "/subledger_cost/",
  CREATESYSCONF: "/system_config_creation/",
  FETCHGLPRIMARY: "/primary_gl/",

  FETCHWH: "/Warehouse_tab/",
  FETCHSUP: "/SUPPLIER_tab/",
  FETCHSUPSITE: "/SUPPLIER_SITE_tab/",
  FETCHPKN: "/PACK_NO_tab/",
  FETCHDIF: "/DIFF_tab/",
  FETCHSKU: "/SKU_tab/",
  FETCHILH: "/item_list_head_tab/",
  FETCHVPN: "/VPN_tab/",
  FETCHUDA: "/UDA_tab/",
  FETCHPO: "/PO_tab/",
  FETCHHIER: "/HIER_tab/",
  FETCHEXCLUDEUDA: "/EXCLUDE_UDA_tab/",
  FETCHALTYPE: "/Alloc_Type_tab/",
  FETCHALLEVEL: "/Alloc_Level_tab/",
  FETCHCNTYPE: "/Context_type_tab/",
  FETCHSTATUS: "/Status_tab/",
  FETCHPROM: "/Promotion_tab/",
  UPDATEALLOCRES: "/Alloc_result_tab/",
  FETCHALOCRITERIA: "/Criteria_tab/",
  UPDATEALLOCINSERT: "/Alloc_Insert_Tab/",
  FETCHITEMPRT: "/ITEM_PARENT_tab/",
  FETCHHIER2: "/HIER2_tab/",
  FETCHHIER3: "/HIER3_tab/",
  UPDATEALLOCRESWH: "/Alloc_result_WH_tab/",
  FETCHASN: "/ASN_tab/",
  UPDATEALLOCRESASN: "/Alloc_result_ASN_tab/",
  FETCHTSF: "/TSF_tab/",
  UPDATEALLOCRESTSF: "/Alloc_result_TSF_tab/",
  FETCHALLOCNO: "/Alloc_No_tab/",
  FETCHALLOCHEADDETAILS: "/Alloc_no_screen_tab/",
  UPDATESELINDCREATE: "/Alloc_update_SelInd_Create_tab/",

  FETCHQTYLIMITS: "/Alloc_qty_limits_retrive_tab/",
  FETCHALLOCNODTLS: "/alloc_no_detail_tab/",
  UPDATEQTYLIMITS: "/update_Alloc_quantity_limits_grid_tab/",
  OKQTYLIMITSSRN: "/alloc_qty_Limits_Insert_tab/",

  FETCHALLOCITEMS: "/allocated_items/",
  INSERTLIKEITEM: "/Insert_LikeItem/",
  FETCHAVAILQTY: "/Alloc_avail_qty_tab/",
  FETCHAVAILSEARCH: "/Alloc_avail_search_tab/",

  FETCHRULETYPE: "/rule_type_code_detail_tab/",
  FETCHNEED: "/need_code_detail_tab/",
  FETCHHIERARCHY: "/hierarchy_code_detail_tab/",
  FETCHALLOCATETO: "/allocate_to_code_detail_tab/",
  FETCHLOCATIONDATA: "/storeData/",
  FETCHLOCATIONRL: "/store_tab/",
  FETCHLOCATIONLISTRL: "/store_list_table/",
  FETCHLOCATIONTRAITSRL: "/store_traits_tab/",
  FETCHCLEARANCERL: "/clearance_code_detail_tab/",
  FETCHSTATUSRL: "/status_code_detail_tab/",
  UPDATERULESRL: "/alloc_rule_Data_tab/",
  FETCHLOCGRID: "/locationGrid/",

  UPDATELOCATIONRL: "/Alloc_update_RL_Location_tab/",
  DELETELOCATIONRL: "/Alloc_delete_RL_Location_tab/",
  LOADWEIGHTCHANGERL: "/Alloc_load_change_weights_tab/",
  LOADRULEDATERL: "/Alloc_load_rule_dates_tab/",
  RETRIEVERULEDATERL: "/Alloc_retrieve_rule_dates_tab/",
  UPDATECHANGEWEIGHTSRL: "/Fetch_Alloc_change_weights_tab/",
  SWITCHTABFUNC: "/switchTab/",

  DELETECREATEGRID: "/Alloc_delete_Create_tab/",

};
