export const headCells = [
  {
    id: "LOC",
    numeric: true,
    disablePadding: false,
    label: "WH",
    width: "100px",
  },
  {
    id: "ITEM",
    numeric: false,
    disablePadding: false,
    label: "Item",
    width: "100%",
  },
  {
    id: "ITEM_DESC",
    numeric: false,
    disablePadding: false,
    label: "Description",
    width: "100%",
  },
  {
    id: "DIFF_ID",
    numeric: false,
    disablePadding: true,
    label: "Diff ID",
    width: "100%",
  },
  {
    id: "VPN",
    numeric: false,
    disablePadding: true,
    label: "VPN",
    width: "100%",
  },
  {
    id: "HIER1",
    numeric: false,
    disablePadding: true,
    label: "Dept",
    width: "100%",
  },
  {
    id: "HIER2",
    numeric: false,
    disablePadding: true,
    label: "Class",
    width: "100%",
  },
  {
    id: "HIER3",
    numeric: false,
    disablePadding: true,
    label: "Subclass",
    width: "100%",
  },
  {
    id: "AVAIL_QTY",
    numeric: false,
    disablePadding: true,
    label: "Avail Qty",
    width: "100%",
  },
  {
    id: "INACTIVE_QTY",
    numeric: true,
    disablePadding: false,
    label: "Inactive Qty",
    width: "100%",
  },
  {
    id: "HOLDBACK_TYPE",
    numeric: true,
    disablePadding: false,
    label: "Doc No",
    width: "100%",
  },
  {
    id: "HOLDBACK_TYPE",
    numeric: true,
    disablePadding: false,
    label: "Doc Type",
    width: "100%",
  },
  {
    id: "PO_TYPE",
    numeric: false,
    disablePadding: false,
    label: "Po Type",
    width: "100%",
  },
  {
    id: "HOLDBACK_TYPE",
    numeric: true,
    disablePadding: false,
    label: "Inner",
    width: "100%",
  },
  {
    id: "HOLDBACK_TYPE",
    numeric: false,
    disablePadding: true,
    label: "Case",
    width: "100%",
  },
  {
    id: "SOM_QTY",
    numeric: true,
    disablePadding: false,
    label: "SOM",
    width: "100%",
  },
  {
    id: "HOLDBACK_QTY",
    numeric: true,
    disablePadding: false,
    label: "Season",
    width: "100%",
  },
  {
    id: "ERR_IND",
    numeric: true,
    disablePadding: false,
    label: "Error Type",
    width: "100%",
  },
  {
    id: "HOLDBACK_QTY",
    numeric: true,
    disablePadding: false,
    label: "TOTAL RETAIL",
    width: "100%",
  },
  {
    id: "ERR_MESSAGE",
    numeric: false,
    disablePadding: true,
    label: "Error Message",
    width: "100%",
  },
];
